# Generated by Django 3.1.3 on 2020-11-13 20:20

import chatapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=chatapp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='seen',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(default='https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/chat_avatar_01.jpg')),
                ('role', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], default='student', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
