const chat_state = {
    chat_1: {
      roomId: 1,
      userName: "Naman tam",
      chatId: 1,
      userId: 1,
      text: "Hello Vikas",
      seen: false,
      imageUrl: "https://google.com",
    },
    chat_2: {
      roomId: 1,
      userName: "Vikas tam",
      chatId: 2,
      userId: 2,
      text: "Why did the web developer leave the restaurant? Because of the table layout.'",
      seen: false,
      imageUrl: "https://google.com",
    },
    chat_3: {
      roomId: 1,
      userName: "Naman tam",
      chatId: 3,
      userId: 1,
      text: "How do you comfort a JavaScript bug? You console it.",
      seen: false,
      imageUrl: "https://google.com",
    },
    chat_4: {
      roomId: 1,
      userName: "Vikas tam",
      chatId: 4,
      userId: 2,
      text: 'An SQL query enters a bar, approaches two tables and asks: "May I join you?"',
      seen: false,
      imageUrl: "https://google.com",
    },
    chat_5: {
      roomId: 1,
      userName: "Naman tam",
      chatId: 5,
      userId: 1,
      text: "What is the most used language in programming? Profanity.",
      seen: false,
      imageUrl: "https://google.com",
    },
    chat_6: {
      roomId: 1,
      userName: "Vikas tam",
      chatId: 6,
      userId: 2,
      text: "What is the object-oriented way to become wealthy? Inheritance.",
      seen: false,
      imageUrl: "https://google.com",
    },
  }